Big change to decision-making process for enabling the pump again after it's turned off. Looking at the return temperature while the pump is off is not reliable at higher tank temperatures (call it 47C and above) - the sensor on the return fitting falls off a cliff for whatever reason, and can't tell if there's hot water at the panel like it can when the tank is cold, again when the pump is off. This change throws all of that out in favour of speculatively running the pump in order to sample the water coming back down from the panel. Once the pump off delay has passed, the pump is turned on and the `TEST_PANEL_HOT` state is invoked to give enough time for water to come down from the roof and heat the fitting if there's hot water available. Once the water is flowing, we can get a better look at what the panel's doing. Recognising that doing this a lot on a cloudy day can result in wasting hot water (warm water pumped from the tank up to the panel, where it cools off) an attempt at an exponential backoff has been made. Each time the pump is turned off and the delay period elapses, the delay period for the next instance is doubled. If the system continuously manages to heat the tank, the prospective delay is gradually reduced linearly over time. This way we ramp up the delay time between samples quickly when there isn't much hot water available from the panel, and reward the system for consistently heating by lowering the delay. Short breaks in an otherwise sunny day should recover quickly, and longer periods of cloud should cause the system to slow its decisions down. Tweaked the start time in the morning to 8:20am. Worked this morning before I started making wholesale changes. Fiddled with the status script to produce test and warning messages on stderr so they don't end up in the running log (which will go away eventually anyway). This hasn't been tested in any signifdicant way yet. It allows the system to start up and run as expected, but there hasn't been enough shade yet this afternoon to test the rate adjustments. Small changes to the y axes of the graphs again. On a really sunny day we can get absolutely enormous spikes (> 90C) on the return line if the pump's been off for a while and the water up top stagnated in direct sun. These were blowing out the graph scale, and aren't that interesting.

diff --git a/water_heater_status b/water_heater_status
--- a/water_heater_status
+++ b/water_heater_status
@@ -19,7 +19,7 @@ PATH="$SCRIPT_DIR:/gpc/bin:$PATH"
 
 # If the status file does not exist, then we're stuffed.
 if [ ! -f "$CONTROL_STATUS_FILE" ] ; then
-  echo "error: Status file '$CONTROL_STATUS_FILE' does not exist."
+  echo "error: Status file '$CONTROL_STATUS_FILE' does not exist." 1>&2
   exit 1  
 fi
 
@@ -28,9 +28,10 @@ fi
 . "$CONTROL_STATUS_FILE"
 
 # The status file should contain an expiry time. Has this elapsed?
+set -x
 now=$(date +%s)
 if [ $now -gt $expiry ] ; then
-  echo "warning: $CONTROL_STATUS FILE indicates info has expired. Currently $now, expiry $expiry."
+  echo "warning: $CONTROL_STATUS FILE indicates info has expired. Currently $now, expiry $expiry." 1>&2
   exit 1
 fi
 
